
development:
  database: 'openenos'
  username: 'sridhar'
  password:	'p@ssw0rd'
  series:
    min_table: 'emon_readings'
    hour_table: 'emon_readings_by_hour'
    runtime_series: 'appliance_runtimes'

production:
  database: 'openenos'
  username: 'enos'
  password:	'p@ssw0rd'
  series:
    min_table: 'emon_readings'
    hour_table: 'emon_readings_by_hour'
    runtime_series: 'appliance_runtimes'
